version: "3.7"
services:
  postgres:
    image: postgres:latest
    container_name: postgres2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postgres